WITH CTE AS (
    SELECT TO_TIMESTAMP(STARTED_AT), 
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT, 
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT, 
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY, 
    {{ day_type('STARTED_AT') }} AS DAY_TYPE,
    MONTH(TO_TIMESTAMP(STARTED_AT)),
    {{ get_season("STARTED_AT") }} AS SEASON
    FROM {{ source('demo', 'bike') }} 
    where STARTED_AT != 'started_at'
)
SELECT * FROM CTE