WITH CTE AS (
    SELECT TO_TIMESTAMP(STARTED_AT), 
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT, 
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT, 
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY, 
    CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun')
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,
    MONTH(TO_TIMESTAMP(STARTED_AT)),
    CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (10,11,12,1)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5,6)
    THEN 'SUMMER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (7,8,9)
    THEN 'MONSOON'
    ELSE 'SPRING'
    END AS SEASON
    FROM {{ source('demo', 'bike') }} 
    where STARTED_AT != 'started_at'
)
SELECT * FROM CTE